Port: 8080
{
  "prediction": [
    20.35373177134412
  ]
}

==== OUTPUTS ====

 * Debugger is active!
 * Debugger PIN: 942-416-625
127.0.0.1 - - [06/May/2023 04:48:13] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [06/May/2023 04:48:14] "GET /favicon.ico HTTP/1.1" 404 -
[2023-05-06 04:50:02,640] INFO in app: JSON payload:
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2023-05-06 04:50:02,657] INFO in app: Inference payload DataFrame:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2023-05-06 04:50:02,668] INFO in app: Scaling Payload:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2023-05-06 04:50:02,673] INFO in app: Prediction INFO: [20.35373177134412]
127.0.0.1 - - [06/May/2023 04:50:02] "POST /predict HTTP/1.1" 200 -

==== FORWARD PORT ====
NAME            READY   STATUS    RESTARTS        AGE
udacity-final   1/1     Running   1 (2m13s ago)   3h21m
Error from server (AlreadyExists): pods "udacity-final" already exists
Forwarding from 127.0.0.1:8080 -> 80
Forwarding from [::1]:8080 -> 80